### ISSUE TITLE
Source Question

### ISSUE THREAD

**Issue by tyeeman** [zupzup/blog-generator#10]
Just came back to this generator and it is very nice. Is it possible to use the current folder that the build exe is in for the source markdown files or even a subfolder which I can name anything I want ? I want to store my source md files locally is the reason.

Is there a simple change I could make so that the meta data is in the top of the post instead of a separate file?

**Comment by zupzup** [comment]
Hey!

In the current version, that doesn't work - however in order to do that, you'd have to implement the DataSource interface with something like a `FileDataSource`.

You could also change the existing `GitDataSource` to simply read the given folder, instead of downloading things from git.

Having metadata on top of the file is probably a bit more involved than a single change. But in `post.go`, you could try to adapt the `getMeta` function to read the beginning of the file.

You would probably also have to edit the `getHTML` function to ignore the top of the file then.

Hope this helps!

**Comment by fbaube** [comment]
I have a fork of zupzup's code that does this - it can read the MD from a local folder tree - but right now the code is kinda broken. You might get some ideas tho. [github.com/fbaube/bloggenator ](http://github.com/fbaube/bloggenator)

**Comment by tyeeman** [comment]
I thought just came to me - can I use http://localhost/folder to read a local folder without changing anything?

**Comment by tyeeman** [comment]
I just tried to update the generator on my system  with the -u command line switch and I'm getting the following error - 

```
c:\goWorkspace>go get github.com/zupzup/blog-generator
# github.com/zupzup/blog-generator/generator
src\github.com\zupzup\blog-generator\generator\generator.go:243:40: too many arguments in call to "g
ithub.com/alecthomas/chroma/formatters/html".WithClasses
        have (bool)
        want ()
```
 Am I doing something wrong?

**Comment by zupzup** [comment]
So, in order to use localhost/folder, you would need to have a git server running there, which seems like more overhead than necessary.

You want to look at the `git.go` file in `datasource`.

There is a `Fetch` method. In this function, if you get rid of the 

```go
	if err := clearFolder(to); err != nil {
		return nil, err
	}
	if err := cloneRepo(to, from); err != nil {
		return nil, err
	}
```
block

Then it should just read the folder and won't delete the files in it / fetch from git anymore.

**Comment by tyeeman** [comment]
Works great, thanks!
